# Generated by Django 2.2.19 on 2021-05-04 15:48

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20210311_1529'),
    ]

    operations = [
    ]
