# Generated by Django 2.2.19 on 2021-05-04 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='survey.Topic', verbose_name='Topic'),
        ),
    ]
