# Generated by Django 2.2.19 on 2021-05-18 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0005_auto_20210518_0301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('msg_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Message number')),
                ('english_message', models.TextField(blank=True, null=True, verbose_name='English Messages')),
                ('arabic_message', models.TextField(blank=True, null=True, verbose_name='Arabic Messages')),
                ('relevant_link', models.URLField(blank=True, null=True, verbose_name='Link to IEC materials')),
                ('adapted_by', models.ManyToManyField(related_name='_message1_adapted_by_+', to='survey.Source', verbose_name='Adapted from Below Source')),
                ('audience', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='survey.Audience', verbose_name='Audience')),
                ('channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='survey.Channel', verbose_name='Channel')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('desired_output', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='survey.Output', verbose_name='Desired behavior / output')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='survey.Language', verbose_name='Language')),
                ('message_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='survey.Type', verbose_name='Type of message / driver')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
                ('sector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='survey.Sector', verbose_name='Sector')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='survey.Topic', verbose_name='Topic')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['msg_number'],
            },
        ),
    ]
