# Generated by Django 2.2.19 on 2021-03-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='adapted_by',
            field=models.ManyToManyField(related_name='_message_adapted_by_+', to='survey.Source', verbose_name='Adapted from Below Source'),
        ),
    ]
